name: "Notify Discord on Push to Main"

on:
  push:
    branches:
      - main  # or replace with your deploy branch

jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord with commit details
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"🚀 Gospel Go (https://gospelgo.org) was updated and is deploying via Netlify!\n**Author**: $COMMIT_AUTHOR\n**Message**: $COMMIT_MESSAGE\"}" \
               $DISCORD_WEBHOOK
